//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class AcumulaFOB
    {
        public int id { get; set; }
        public string idCliente { get; set; }
        public string userRegistro { get; set; }
        public Nullable<decimal> valorAcumulado { get; set; }
        public Nullable<System.DateTime> fechaRegistro { get; set; }
        public int restiradoEstado { get; set; }
    }
}
