//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class CatalogoRecompensa
    {
        public int idCatalogo { get; set; }
        public string idImgCatalog { get; set; }
        public Nullable<int> puntos { get; set; }
        public string nombreUnico { get; set; }
        public string codigoCange { get; set; }
        public Nullable<int> cantidadProdcuto { get; set; }
        public Nullable<int> estadoProducto { get; set; }
        public Nullable<int> eliminado { get; set; }
    }
}
