//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class CodigosPromocionales
    {
        public string codPromocional { get; set; }
        public Nullable<System.DateTime> fechaInicio { get; set; }
        public Nullable<System.DateTime> fechaFin { get; set; }
        public Nullable<bool> estado { get; set; }
        public string tipoCodigo { get; set; }
        public Nullable<System.DateTime> fechaRegistro { get; set; }
        public string usuarioRegistro { get; set; }
        public Nullable<decimal> valorVenta { get; set; }
        public Nullable<decimal> descuento { get; set; }
        public Nullable<int> limitesUso { get; set; }
        public Nullable<decimal> valorMaximo { get; set; }
    }
}
