//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class CupDescCab
    {
        public CupDescCab()
        {
            this.CupDescDet = new HashSet<CupDescDet>();
        }
    
        public int idDescCab { get; set; }
        public string numCupDesc { get; set; }
        public string detDesc { get; set; }
        public double valorDescPor { get; set; }
        public string usuarioRegistro { get; set; }
        public System.DateTime fechaRegistro { get; set; }
        public System.DateTime fechaIni { get; set; }
        public System.DateTime fechaFin { get; set; }
    
        public virtual ICollection<CupDescDet> CupDescDet { get; set; }
    }
}
