//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class CupDescDet
    {
        public int idDescDet { get; set; }
        public int idDescCab { get; set; }
        public string detDesc { get; set; }
        public string idOrdenEnvio { get; set; }
        public string usuarioRegistro { get; set; }
        public string numIden { get; set; }
        public System.DateTime fechaRegistro { get; set; }
    
        public virtual CupDescCab CupDescCab { get; set; }
    }
}
