//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class IngresoImpuesto
    {
        public int idImp { get; set; }
        public string tipoPago { get; set; }
        public string observacion { get; set; }
        public string identificacionCliente { get; set; }
        public string estadoOrden { get; set; }
        public Nullable<decimal> totalPesoImp { get; set; }
        public System.DateTime fechaRegistro { get; set; }
        public Nullable<decimal> pagoImpuesto { get; set; }
        public string numCodigoImp { get; set; }
        public string usuarioRegistro { get; set; }
    }
}
