//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class MenuApp
    {
        public MenuApp()
        {
            this.SEGRolesTransaccion = new HashSet<SEGRolesTransaccion>();
        }
    
        public int id_nivel { get; set; }
        public string descripcion { get; set; }
        public Nullable<int> id_padre { get; set; }
        public string url { get; set; }
        public Nullable<bool> estado { get; set; }
        public string permisoVisualizacion { get; set; }
        public string CssFont { get; set; }
    
        public virtual ICollection<SEGRolesTransaccion> SEGRolesTransaccion { get; set; }
    }
}
