//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentsGet
    {
        public int idPay { get; set; }
        public string estado { get; set; }
        public string cid { get; set; }
        public string idorden { get; set; }
        public Nullable<System.DateTime> fechaRegistro { get; set; }
    }
}
