//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProdContifico
    {
        public string id { get; set; }
        public string nombre { get; set; }
        public Nullable<decimal> precio { get; set; }
        public Nullable<int> porcentajeIva { get; set; }
        public Nullable<decimal> porcentajeDesc { get; set; }
        public Nullable<decimal> baseCero { get; set; }
        public Nullable<decimal> baseGrav { get; set; }
        public Nullable<decimal> basenoGrav { get; set; }
        public Nullable<decimal> valIce { get; set; }
        public Nullable<decimal> porcIce { get; set; }
        public string categoria { get; set; }
        public Nullable<System.DateTime> fechaRegistro { get; set; }
        public string usuarioRegistro { get; set; }
        public int restiradoEstado { get; set; }
    }
}
