//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class SEGRolesTransaccion
    {
        public int id_nivel { get; set; }
        public string descripcionMenu { get; set; }
        public string codTransaccion { get; set; }
        public int id_rol { get; set; }
        public string descripcionRol { get; set; }
    
        public virtual MenuApp MenuApp { get; set; }
        public virtual Roles Roles { get; set; }
    }
}
