//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class TiposEnvio
    {
        public int idTipoEnv { get; set; }
        public Nullable<int> idEnvio { get; set; }
        public string numSeguim { get; set; }
        public string empresa { get; set; }
        public Nullable<System.DateTime> fechaRegistroCliente { get; set; }
        public string userRegistro { get; set; }
    }
}
