//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuarios
    {
        public string cod_usu { get; set; }
        public string identificacion { get; set; }
        public string password { get; set; }
        public Nullable<bool> cambio_clave { get; set; }
        public Nullable<System.DateTime> fecha_cambio_clave { get; set; }
        public int privilegiado { get; set; }
    }
}
